### ISSUE TITLE
How to register a sintel account？

### ISSUE THREAD

**Issue by AMiaoJF** [xiaofeng94/GMFlowNet#5]
I know this question is ridiculous. I have tried all kinds of methods, but still no registration is successful. I tried to sign up with school email and google email, but it didn't work. The following information will pop up. I have also sent an email to [sintel@tue.mpg.de](mailto:sintel@tue.mpg.de), but have never received a reply. How did you sign up for a sintel account?
<img width="1088" alt="ef8bbae616ab13902bb098d31a03a7b" src="https://user-images.githubusercontent.com/113485477/190047914-aeddee88-4661-4a33-b8a6-ebfd80a13fb7.png">

**Comment by xiaofeng94** [comment]
Hey, does your email domain end exactly with `.edu` ?

**Comment by AMiaoJF** [comment]
I have tried using the school mailbox. The email domain name ends with .edu.cn.

**Comment by AMiaoJF** [comment]
> Hey, does your email domain end exactly with `.edu` ?

I have tried using the school mailbox. The email domain name ends with `.edu.cn`.

**Comment by xiaofeng94** [comment]
Possibly, the website doesn't recognize domains ending with `.edu.cn`. You may need to contact them to add your domain.

**Comment by AMiaoJF** [comment]
Thank you very much for your help. I successfully registered with an email address ending with `.edu`.
